POST http://localhost:3333/users
Content-Type: 'application/json 

{
  "name":"teste middleware 8",
  "email":"example2@gmail.com",
  "password":"123456"
}

###
GET http://localhost:3333/users
Content-Type: 'application/json'

###
DELETE http://localhost:3333/users
Content-Type: 'application/json'


###
POST http://localhost:3333/users/session
Content-Type: 'application/json'